"""add_analytics_tables

Revision ID: f61f47fb2876
Revises: f859aa21abf4
Create Date: 2025-12-05 15:38:12.092372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f61f47fb2876"
down_revision: Union[str, None] = "f859aa21abf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="chess",
    )

    op.create_table(
        "analysis_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.String(length=255), nullable=False),
        sa.Column("analytic_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analytic_id"], ["chess.analytics_types.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["chess.games.game_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="chess",
    )

    op.create_index(
        "ix_analysis_status_game_analytic",
        "analysis_status",
        ["game_id", "analytic_id"],
        unique=True,
        schema="chess",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_game_metrics_metrics",
        table_name="game_metrics",
        schema="chess",
        postgresql_using="gin",
    )
    op.drop_table("analysis_status", schema="chess")
    op.drop_table("analytics_types", schema="chess")
    # ### end Alembic commands ###
