"""Add game_features table

Revision ID: 32e988bbc696
Revises: 202511251700
Create Date: 2025-11-26 22:19:03.524464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32e988bbc696'
down_revision: Union[str, None] = '202511251700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_features',
    sa.Column('game_id', sa.Text(), nullable=False),
    sa.Column('feature_name', sa.Text(), nullable=False),
    sa.Column('feature_value', sa.Text(), nullable=False),
    sa.Column('feature_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['chess.games.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'feature_name'),
    schema='chess'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_features', schema='chess')
    # ### end Alembic commands ###
